# Generated by Django 6.0.7 on 2026-07-27 22:21

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
    ]
