# Generated by Django 5.2.16 on 2026-09-06 14:56, reescrita manualmente
# para trocar o default do campo de True para False: default=True cobriria
# qualquer create_user(), inclusive fixtures de teste de outros apps. "Todo
# usuário já existente troca no próximo login" vira uma migração de dados
# explícita (RunPython); "todo usuário novo criado pelo admin nasce
# marcado" vira código explícito em UsuarioAdmin.save_model
# (core/admin.py), não mais o default.

from django.db import migrations, models


def marcar_usuarios_existentes_para_troca_de_senha(apps, schema_editor):
    """Marca só as linhas já presentes na tabela no momento desta
    migração; num banco novo a tabela está vazia neste ponto, então não
    marca nada."""
    Usuario = apps.get_model("core", "Usuario")
    Usuario.objects.update(senha_temporaria=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='senha_temporaria',
            field=models.BooleanField(default=False, verbose_name='exige troca de senha no próximo acesso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha_temporaria',
            field=models.BooleanField(default=False, verbose_name='exige troca de senha no próximo acesso'),
        ),
        migrations.RunPython(
            marcar_usuarios_existentes_para_troca_de_senha,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
