# Generated by Django 5.2.16 on 2026-07-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'classificação',
                'verbose_name_plural': 'classificações',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrauPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'grau de prioridade',
                'verbose_name_plural': 'graus de prioridade',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentoContratual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'instrumento contratual',
                'verbose_name_plural': 'instrumentos contratuais',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'modalidade',
                'verbose_name_plural': 'modalidades',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SituacaoNormalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'situação normalizada',
                'verbose_name_plural': 'situações normalizadas',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'tipo de contratação',
                'verbose_name_plural': 'tipos de contratação',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('nome_normalizado', models.CharField(db_index=True, editable=False, max_length=255, unique=True, verbose_name='nome normalizado')),
            ],
            options={
                'verbose_name': 'unidade organizacional',
                'verbose_name_plural': 'unidades organizacionais',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
    ]
