# Generated by Django 5.2.16 on 2026-08-04 01:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import DEFAULT_DB_ALIAS, migrations, models


def backfill_reunioes(apps, schema_editor):
    """Cria uma `Reuniao` por data de referência distinta já importada e
    associa cada `Acompanhamento` retroativamente; nascem fechadas.
    Idempotente via `get_or_create(data=...)`."""
    Acompanhamento = apps.get_model("pca", "Acompanhamento")
    Reuniao = apps.get_model("pca", "Reuniao")
    db = (
        schema_editor.connection.alias
        if schema_editor is not None
        else DEFAULT_DB_ALIAS
    )

    # .order_by() explícito evita que o Meta.ordering de Acompanhamento
    # entre no SELECT e quebre o DISTINCT.
    datas = (
        models.QuerySet(model=Acompanhamento, using=db)
        .order_by()
        .values_list("referencia_data", flat=True)
        .distinct()
    )

    for data in sorted(datas):
        reuniao, _ = Reuniao.objects.using(db).get_or_create(
            data=data, defaults={"situacao": "fechada"}
        )
        # `.update()` do QuerySet base do Django: em tempo de migração o
        # manager auditado da app não existe no model histórico.
        (
            models.QuerySet(model=Acompanhamento, using=db)
            .filter(referencia_data=data, reuniao__isnull=True)
            .update(reuniao_id=reuniao.pk)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0002_unaccent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 8, 4, 1, 5, 49, 811431, tzinfo=datetime.timezone.utc), editable=False, verbose_name='atualizado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da reunião')),
                ('situacao', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=10, verbose_name='situação')),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reunioes_conduzidas', to=settings.AUTH_USER_MODEL, verbose_name='condutor')),
            ],
            options={
                'verbose_name': 'reunião',
                'verbose_name_plural': 'reuniões',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='reuniao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompanhamentos', to='pca.reuniao', verbose_name='reunião'),
        ),
        migrations.AddField(
            model_name='historicalacompanhamento',
            name='reuniao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pca.reuniao', verbose_name='reunião'),
        ),
        # Reverso noop: desfazer a migração já derruba tabela e coluna
        # criadas aqui.
        migrations.RunPython(backfill_reunioes, migrations.RunPython.noop),
    ]
