# Generated by Django 5.2.16 on 2026-08-04 02:01

from django.contrib.auth.management import create_permissions
from django.apps import apps as django_apps
from django.db import migrations


def criar_grupos_e_permissao(apps, schema_editor):
    """Cria os perfis do PCA (grupos e permissão) sem depender do
    post_migrate."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # O Apps histórico da migration não expõe models_module; usa o
    # AppConfig real.
    create_permissions(django_apps.get_app_config("pca"), verbosity=0)
    grupo_editor, _ = Group.objects.get_or_create(name="editor")
    Group.objects.get_or_create(name="visualizador")
    permissao = Permission.objects.get(
        codename="editar_pca", content_type__app_label="pca"
    )
    grupo_editor.permissions.add(permissao)


def preservar_grupos_e_permissao(apps, schema_editor):
    # Remover grupos no rollback poderia destruir atribuições reais de usuários.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0003_reuniao_versao_otimista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['item_pca'], 'permissions': [('editar_pca', 'Pode editar processos, mover kanban e registrar acompanhamento')], 'verbose_name': 'processo', 'verbose_name_plural': 'processos'},
        ),
        migrations.RunPython(
            criar_grupos_e_permissao,
            preservar_grupos_e_permissao,
        ),
    ]
