# Generated by Django 5.2.16 on 2026-08-04 18:32

import apps.pca.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0005_invariantes_reuniao_alocador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocesso',
            name='fornecedor_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='Informe um valor válido.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$'), apps.pca.validators.validar_digitos_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fornecedor_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='Informe um valor válido.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$'), apps.pca.validators.validar_digitos_cnpj], verbose_name='CNPJ'),
        ),
    ]
