# Generated by Django 5.2.16 on 2026-08-05 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_exercicio'),
        ('pca', '0010_rascunho_virada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='nome do arquivo')),
                ('processos_criados', models.PositiveIntegerField(default=0, verbose_name='processos criados')),
                ('acompanhamentos_criados', models.PositiveIntegerField(default=0, verbose_name='acompanhamentos criados')),
                ('relatorio_caminho', models.CharField(blank=True, default='', max_length=500, verbose_name='caminho do relatório')),
                ('disparado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_importacao', to=settings.AUTH_USER_MODEL, verbose_name='disparado por')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_importacao', to='catalogo.exercicio', verbose_name='exercício')),
            ],
            options={
                'verbose_name': 'evento de importação',
                'verbose_name_plural': 'eventos de importação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
