# Generated by Django 5.2.16 on 2026-08-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0011_eventoimportacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='pca.processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivados', to='pca.processo', verbose_name='processo de origem'),
        ),
        migrations.AlterField(
            model_name='rascunhoitemvirada',
            name='processo_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rascunho_virada', to='pca.processo', verbose_name='processo de origem'),
        ),
    ]
