# Generated by Django 5.2.16 on 2026-08-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0012_alter_acompanhamento_processo_alter_processo_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='justificativa_alteracao_prazo',
            field=models.TextField(blank=True, default='', verbose_name='justificativa de alteração do prazo de envio'),
        ),
        migrations.AddField(
            model_name='processo',
            name='justificativa_alteracao_prazo',
            field=models.TextField(blank=True, default='', verbose_name='justificativa de alteração do prazo de envio'),
        ),
    ]
