# Generated by Django 5.2.16 on 2026-08-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0013_historicalprocesso_justificativa_alteracao_prazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista para entrega'),
        ),
        migrations.AddField(
            model_name='processo',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista para entrega'),
        ),
    ]
