# Generated by Django 5.2.16 on 2026-08-12 03:24
# RunPython manual inserido antes das quatro RemoveField autogeradas pelo
# makemigrations.

from django.db import DEFAULT_DB_ALIAS, migrations, models
from django.utils import timezone


def migrar_justificativa_para_ultima_promessa(apps, schema_editor):
    """Transfere o texto de `justificativa_alteracao_prazo` para o `evento`
    da promessa mais recente do processo, com snapshot
    `HistoricalAcompanhamento` auditado, antes de remover os campos
    obsoletos. Fail-closed: se algum processo não tiver promessa de destino,
    a migração aborta sem gravar nada. Texto vazio não altera; evento vazio
    recebe o texto; texto igual não duplica; texto diferente é anexado."""
    Processo = apps.get_model("pca", "Processo")
    Acompanhamento = apps.get_model("pca", "Acompanhamento")
    HistoricalAcompanhamento = apps.get_model("pca", "HistoricalAcompanhamento")
    db = (
        schema_editor.connection.alias
        if schema_editor is not None
        else DEFAULT_DB_ALIAS
    )

    # `models.QuerySet` base: o manager auditado da app não existe no
    # estado histórico da migração.
    processos_com_texto = (
        models.QuerySet(model=Processo, using=db)
        .order_by("pk")
        .exclude(justificativa_alteracao_prazo="")
        .only("id", "justificativa_alteracao_prazo")
    )

    pendentes = []
    sem_destino = []
    for processo in processos_com_texto:
        texto = (processo.justificativa_alteracao_prazo or "").strip()
        if not texto:
            continue
        promessa = (
            models.QuerySet(model=Acompanhamento, using=db)
            .filter(processo_id=processo.pk, prazo_prometido__isnull=False)
            .order_by("-referencia_data", "-id")
            .first()
        )
        if promessa is None:
            sem_destino.append(processo.pk)
            continue
        pendentes.append((promessa, texto))

    if sem_destino:
        raise RuntimeError(
            "justificativa_alteracao_prazo sem promessa de destino para "
            f"Processo(s) {sorted(sem_destino)} — migração 0015 abortada "
            "antes de remover os campos obsoletos. Corrigir os dados de "
            "origem (registrar uma promessa com prazo_prometido) antes de "
            "reaplicar a migração."
        )

    # Campos concretos lidos dinamicamente do model, via `attname` (nome de
    # coluna correto para campo simples ou FK), para nunca desalinhar do
    # modelo real.
    campos_snapshot = [
        campo.attname
        for campo in Acompanhamento._meta.get_fields()
        if getattr(campo, "concrete", False) and not campo.many_to_many
    ]

    for promessa, texto in pendentes:
        evento_atual = promessa.evento or ""
        evento_atual_limpo = evento_atual.strip()
        if not evento_atual_limpo:
            novo_evento = texto
        elif evento_atual_limpo == texto:
            novo_evento = evento_atual
        else:
            novo_evento = f"{evento_atual_limpo}\n{texto}"

        if novo_evento == evento_atual:
            continue

        models.QuerySet(model=Acompanhamento, using=db).filter(pk=promessa.pk).update(
            evento=novo_evento
        )
        promessa.evento = novo_evento
        snapshot = {campo: getattr(promessa, campo) for campo in campos_snapshot}
        HistoricalAcompanhamento.objects.using(db).create(
            **snapshot,
            history_date=timezone.now(),
            history_type="~",
            history_change_reason="Migração da justificativa de prazo do Processo",
            history_user=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0014_prazo_entrega'),
    ]

    operations = [
        # A reversão não é fiel: texto já anexado a `evento` não se separa
        # de volta de forma unívoca.
        migrations.RunPython(
            migrar_justificativa_para_ultima_promessa, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='justificativa_alteracao_email',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='justificativa_alteracao_prazo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='justificativa_alteracao_email',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='justificativa_alteracao_prazo',
        ),
    ]
