# Generated by Django 5.2.16 on 2026-08-17 15:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_exercicio'),
        ('pca', '0016_permissao_editar_pca_sem_kanban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocesso',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='classificacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.classificacao', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_assinatura_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data assinatura do contrato'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_entrega_delic',
            field=models.DateField(blank=True, null=True, verbose_name='Data entrega no Delic'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_envio_delic',
            field=models.DateField(blank=True, null=True, verbose_name='Data envio ao Delic'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_inclusao_pca',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inclusão no PCA'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_lancamento_dados_abertos',
            field=models.DateField(blank=True, null=True, verbose_name='Data lançamento Dados Abertos'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_lancamento_spw',
            field=models.DateField(blank=True, null=True, verbose_name='Data lançamento SPW'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_lancamento_wordpress',
            field=models.DateField(blank=True, null=True, verbose_name='Data lançamento WordPress'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_prevista_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista/conclusão da contratação'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='data_recebimento_processo',
            field=models.DateField(blank=True, null=True, verbose_name='Data recebimento do processo'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='descricao_objeto',
            field=models.TextField(verbose_name='Descrição do objeto'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='fornecedor_razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='grau_prioridade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.grauprioridade', verbose_name='Grau de prioridade'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='instrumento_contratual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.instrumentocontratual', verbose_name='Instrumento contratual'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='justificativa',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='mes_previsto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês previsto (PCA)'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='modalidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.modalidade', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='numero_arp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da ARP'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='numero_contratacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da contratação'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='numero_instrumento_contratual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do instrumento contratual'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='situacao_sei',
            field=models.CharField(blank=True, choices=[('autuado', 'Autuado'), ('a_autuar', 'A autuar'), ('nao_se_aplica', 'Não se aplica')], default='', max_length=15, verbose_name='Situação do SEI'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.tipo', verbose_name='Tipo de contratação'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='unidade_organizacional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.unidade', verbose_name='Unidade organizacional (UO)'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='valor_contratado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor contratado (R$)'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor estimado (R$)'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='vigencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência fim'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='vigencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência início'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='catalogo.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='catalogo.classificacao', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_assinatura_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data assinatura do contrato'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_entrega_delic',
            field=models.DateField(blank=True, null=True, verbose_name='Data entrega no Delic'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_envio_delic',
            field=models.DateField(blank=True, null=True, verbose_name='Data envio ao Delic'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_inclusao_pca',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inclusão no PCA'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_lancamento_dados_abertos',
            field=models.DateField(blank=True, null=True, verbose_name='Data lançamento Dados Abertos'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_lancamento_spw',
            field=models.DateField(blank=True, null=True, verbose_name='Data lançamento SPW'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_lancamento_wordpress',
            field=models.DateField(blank=True, null=True, verbose_name='Data lançamento WordPress'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_prevista_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista/conclusão da contratação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_recebimento_processo',
            field=models.DateField(blank=True, null=True, verbose_name='Data recebimento do processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao_objeto',
            field=models.TextField(verbose_name='Descrição do objeto'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fornecedor_razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='grau_prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='catalogo.grauprioridade', verbose_name='Grau de prioridade'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='instrumento_contratual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='catalogo.instrumentocontratual', verbose_name='Instrumento contratual'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='justificativa',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='mes_previsto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês previsto (PCA)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='catalogo.modalidade', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_arp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da ARP'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_contratacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da contratação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_instrumento_contratual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do instrumento contratual'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='situacao_sei',
            field=models.CharField(blank=True, choices=[('autuado', 'Autuado'), ('a_autuar', 'A autuar'), ('nao_se_aplica', 'Não se aplica')], default='', max_length=15, verbose_name='Situação do SEI'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='catalogo.tipo', verbose_name='Tipo de contratação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='unidade_organizacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='catalogo.unidade', verbose_name='Unidade organizacional (UO)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_contratado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor contratado (R$)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor estimado (R$)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='vigencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência fim'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='vigencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência início'),
        ),
    ]
