# Generated by Django 5.2.16 on 2026-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0017_rotulos_modal_sentenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocesso',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('nao_iniciado', 'Não iniciado'), ('em_tramitacao', 'Em tramitação'), ('vigente', 'Vigente'), ('cancelado', 'Cancelado'), ('aguardando_dfd', 'Aguardando DFD'), ('finalizado', 'Concluído não contratado')], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('nao_iniciado', 'Não iniciado'), ('em_tramitacao', 'Em tramitação'), ('vigente', 'Vigente'), ('cancelado', 'Cancelado'), ('aguardando_dfd', 'Aguardando DFD'), ('finalizado', 'Concluído não contratado')], max_length=20, verbose_name='status'),
        ),
    ]
